// bgs-angular/src/app/shared/navbar/navbar.component.ts
import { WebshopCartService } from 'src/app/services/webshop-cart.service';
import { Component, Input } from '@angular/core';
import { Subscription } from 'rxjs';

export interface INavbarNavItem {
    onclick: () => void
    text: string
}

@Component({
    selector: 'app-navbar',
    templateUrl: './navbar.component.html',
    styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {
    @Input('navitems') navItems: INavbarNavItem[]
    private cartContentChangeSubscription: Subscription
    public cart: number = 0

    constructor(
        private cartService: WebshopCartService
    ) {
        this.cart = this.cartService.getCartContent().length
    }

    ngOnInit(): void {
        this.cartContentChangeSubscription = this.cartService.cartContentChangeEvent
            .subscribe(() => this.onCartContentChange())
    }

    ngOnDestroy(): void {
        this.cartContentChangeSubscription?.unsubscribe()
    }


    private onCartContentChange(): void {
       this.cart = this.cartService.getCartContent().length
    }
}

<nav class="d-flex align-center">
    <div class="logo">
        <img src="assets/bgs-transparent.png" height="30" class="d-inline-block align-top cursor-pointer" alt="logo">
    </div>

    <div class="items-container d-flex justify-between align-center">
        <div class="nav-links d-flex align-center">
            <ng-container *ngFor="let item of navItems">
                <a class="nav-link" (click)="item.onclick()">{{item.text}}</a>
            </ng-container>
        </div>

        <div class="actions">
            <div class="webshop-cart cursor-pointer">
                <i class="bi bi-cart3"></i>
                <span class="items d-flex justify-center align-center">{{cart}}</span>
            </div>
        </div>
    </div>
</nav>

// bgs-frontend/src/shared/Navbar.tsx
import { IJsxElement } from "../types/general-types";
import { WebshopCart } from "./WebshopCart";
import { For } from "solid-js";
import './Navbar.scss';

export interface INavbarLink {
    onclick: () => void
    text: string
}

export interface INavbarProps {
    links: INavbarLink[]
}

export function Navbar(props: INavbarProps): IJsxElement {
    let smallView: HTMLDivElement | undefined

    function toggleSmallView(): void {
        smallView?.classList.contains('open') ? smallView.classList.remove('open') : smallView?.classList.add('open')
    }

    return (<>
        <nav class="d-flex justify-between align-center">
            <div class="left-side d-flex align-center">
                <img class="mr-4" src="src/assets/bgs-transparent.png" alt="company logo" />

                <i class="bi bi-list cursor-pointer" onClick={toggleSmallView}></i>

                <div class="nav-links d-flex align-center">
                    <For each={props.links}>{x => 
                        <div class="nav-link" onClick={x.onclick}>{x.text}</div>
                    }</For>
                </div>
            </div>

            <div class="right-side">
                <WebshopCart />
            </div>
        </nav>

        <div ref={smallView} class="small-window-links d-flex column pt-2">
            <For each={props.links}>{x => 
                <div class="nav-link" onClick={x.onclick}>{x.text}</div>
            }</For>
        </div>
    </>)
}
