// bgs-frontend/src/BitForm/FileInput.tsx
import { IJsxElement } from "../types/general-types";
import { createSignal, For } from "solid-js";
import './FileInput.scss';

export interface IFileInputProps {
    onChange: (files: File[]) => void
}

export function FileInput(props: IFileInputProps): IJsxElement {
    const [attachments, setAttachments] = createSignal<string[]>([])
    let fileInput: HTMLInputElement | undefined

    function onFileSelect(files: FileList | null | undefined): void {
        let filelist: File[] = [ ]

        if (files) {
            for (let i = 0; i < files.length; i++) {
                filelist.push(files.item(i) as File)
            }
        }

        setAttachments(filelist.map(f => f.name))
        props.onChange(filelist);

        (fileInput as HTMLInputElement).value = ''
    }

    function prevent(event: Event): void {
        event?.stopPropagation(); event?.preventDefault()
    }

    function onDrop(event: DragEvent) {
        event?.stopPropagation(); event?.preventDefault()
        onFileSelect(event?.dataTransfer?.files)
    }

    function selectFiles(): void {
        fileInput?.click()
    }

    return (<div class="bit-file-input-container">
        <input ref={fileInput} type="file" class="d-none" multiple onChange={e => onFileSelect(e.currentTarget.files)} />
        <div class="file-drop-area cursor-pointer d-flex justify-center align-center" onClick={selectFiles} onDrop={e => onDrop(e)} onDragOver={e => prevent(e)}>
            <i class="bi bi-cloud-arrow-up"></i>
        </div>

        <div class="selected-files-container d-flex">
            <For each={attachments()}>{x =>
                <span class="selectedfile">{x}</span>
            }</For>
        </div>
    </div>)
}

// bgs-angular/src/app/bitform/file-input/file-input.component.ts
import { Component, ElementRef, EventEmitter, HostListener, Output, ViewChild } from '@angular/core';

@Component({
    selector: 'file-input',
    templateUrl: './file-input.component.html',
    styleUrls: ['./file-input.component.scss']
})
export class FileInputComponent {
    @ViewChild('fileinput', {static: true}) fileInputRef: ElementRef<HTMLInputElement>
    @Output('filesSelected') public filesSelectedEmitter = new EventEmitter()
    public files: File[] = [ ]

    constructor() { }


    public get fileInput(): HTMLInputElement {
        return this.fileInputRef.nativeElement
    }

    public onClick(): void {
        this.fileInput.click()
    }

    public onFileinputChange(event: Event): void {
        const target = event?.target as HTMLInputElement
        this.setValue(target?.files)
    }

    @HostListener('drop', ['$event'])
    public onDrop(event: DragEvent): void {
        event.preventDefault(); event.stopPropagation()
        this.setValue(event.dataTransfer?.files)
    }

    @HostListener('dragover', ['$event'])
    @HostListener('dragleave', ['$event'])
    public preventEvent(event: Event): void {
        event.preventDefault(); event.stopPropagation()
    }

    public setValue(fileList: FileList | null | undefined): void {
        this.fileInput.files = null
        this.files = [ ]

        if (fileList instanceof FileList) {
            for (let i = 0; i < fileList.length; i++) {
                this.files.push(fileList.item(i) as File)
            }
        }

        this.filesSelectedEmitter.emit(fileList)
    }
}

<div class="file-input-container" (click)="onClick()">
    <i class="bi bi-cloud-upload-fill"></i>
</div>
<div class="file-list">
    <div *ngFor="let file of files" class="file">{{file.name}}</div>
</div>

<div hidden>
    <input #fileinput multiple type="file" (change)="onFileinputChange($event)">
</div>
