// bgs-frontend/src/Galerie/Galeries.tsx
import { getImageLinkFromFileList } from "../helpers/drive-image-helper";
import { IDetailedGalery } from "../types/galery-types";
import { navigate } from "../helpers/navigation-helper";
import { INavbarLink, Navbar } from "../shared/Navbar";
import { createSignal, For, onMount } from "solid-js";
import { GalerieModal } from "../Modals/GalerieModal";
import { IJsxElement } from "../types/general-types";
import { openModal } from "../Modals/modal.service";
import { useNavigate } from "@solidjs/router";
import { BitImage } from "../shared/BitImage";
import { Get } from "../helpers/http";
import './Galeries.scss';

export function Galeries(): IJsxElement {
    const [galeries, setGaleries] = createSignal<IDetailedGalery[]>()
    const links: INavbarLink[] = [
        {text: 'Kezdőlap', onclick: () => navigate(navigator, '/')},
        {text: 'Webshop', onclick: () => navigate(navigator, '/webshop')}
    ]
    const navigator = useNavigate()

    onMount(() => getGaleries())

    function getGaleries(): void {
        Get<IDetailedGalery[]>('galeries')
            .then(response => {
                setGaleries(response)
            })
            .catch(error => { })
    }

    function openGaleriemodal(id: number): void {
        openModal(() => GalerieModal({galerieid: id}))
    }

    return (
        <div class="galeries-page-container">
            <Navbar links={links} />

            <div class="galeries-page-content d-flex justify-center p-4">
                <div class="galeries-list d-grid">
                    <For each={galeries()}>{x =>
                        <div class="col-12 pb-4">
                            <div class="d-grid">
                                <div class="col-md-6 col-sm-12 d-flex column">
                                    <h3 class="pb-2">{x.name}</h3>
                                    <p>{x.description}</p>
                                    <div class="d-flex justify-start pt-4">
                                        <button class="btn-grey-thin" onClick={() => openGaleriemodal(x.id as number)}>Összes kép megtekintése</button>
                                    </div>
                                </div>

                                <div class="image-container d-flex justify-center col-md-6 col-sm-12 width-100">
                                    <BitImage src={getImageLinkFromFileList(x.files)}></BitImage>
                                </div>
                            </div>
                        </div>
                    }</For>
                </div>
            </div>
        </div>
    )
}

// bgs-angular/src/app/visitor/galeries/galeries.component.ts
import { INavbarNavItem } from 'src/app/shared/navbar/navbar.component';
import { HttpService } from 'src/app/services/http.service';
import { IGalery } from 'src/app/types/galery-types';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
    selector: 'app-galeries',
    templateUrl: './galeries.component.html',
    styleUrls: ['./galeries.component.scss']
})
export class GaleriesComponent implements OnInit {
    public navItems: INavbarNavItem[] = [
        {text: 'Kezdő oldal', onclick: () => this.router.navigateByUrl('/')}
    ]
    public galeries: IGalery[] = [ ]

    constructor(
        private http: HttpService,
        private router: Router
    ) { }

    ngOnInit(): void {
        this.getGaleries()
    }


    private getGaleries(): void {
        this.http.get<IGalery[]>('galeries')
            .then(response => {
                this.galeries = response.filter(g => g.files?.length > 0)
            })
            .catch(error => { })
    }

}

<app-navbar [navitems]="navItems"></app-navbar>

<div class="galeries-container d-flex flex-column align-items-center">

    <div class="card mb-3" *ngFor="let galery of galeries">
        <div class="row g-0">
            <div class="col-md-8">
                <img src="{{galery.files[0].fileid | driveImg}}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-4">
                <div class="d-flex flex-column justify-content-between h-100">
                    <div class="d-flex flex-column p-3 pb-0">
                        <h5 class="card-title text-center">{{galery.name}}</h5>

                        <p class="card-text">{{galery.description}}</p>
                    </div>

                    <div class="d-flex justify-content-center pt-2 pb-2">
                        <button class="btn btn-dark" routerLink="/galeria/{{galery.id}}">Megnyitás</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
